class BibleConstants {
  static const Map<String, String> bookNames = {
    'GEN': '창세기',
    'EXOD': '출애굽기',
    'LEV': '레위기',
    'NUM': '민수기',
    'DEUT': '신명기',
    'JOSH': '여수아',
    'JUDG': '사사기',
    'RUTH': '루스기',
    '1SAM': '사무엘상',
    '2SAM': '사무엘하',
    '1KGS': '열왕기상',
    '2KGS': '열왕기하',
    '1CHR': '역대상',
    '2CHR': '역대하',
    'EZRA': '에스라',
    'NEH': '느헤미야',
    'ESTH': '에스더',
    'JOB': '욥기',
    'PSAL': '시편',
    'PROV': '잠언',
    'ECCL': '전도서',
    'SONG': '아가',
    'ISA': '이사야',
    'JER': '예레미야',
    'LAM': '예레미야 애가',
    'EZEK': '에스겔',
    'DAN': '다니엘',
    'HOS': '호세아',
    'JOEL': '요엘',
    'AMOS': '아모스',
    'OBAD': '오바댜',
    'JONAH': '요나',
    'MIC': '미가',
    'NAH': '나훔',
    'HAB': '하박국',
    'ZEPH': '스바냐',
    'HAG': '학개',
    'ZECH': '스가랴',
    'MAL': '말라기',
    'MATT': '마태복음',
    'MARK': '마가복음',
    'LUKE': '누가복음',
    'JOHN': '요한복음',
    'ACTS': '사도행전',
    'ROM': '로마서',
    '1COR': '고린도전서',
    '2COR': '고린도후서',
    'GAL': '갈라디아서',
    'EPH': '에베소서',
    'PHIL': '빌립보서',
    'COL': '골로새서',
    '1THESS': '데살로니가전서',
    '2THESS': '데살로니가후서',
    '1TIM': '디모데전서',
    '2TIM': '디모데후서',
    'TITUS': '디도서',
    'PHILEM': '빌레몬서',
    'HEB': '히브리어',
    'JAS': '야고보서',
    '1PET': '베드로전서',
    '2PET': '베드로후서',
    '1JOHN': '요한일서',
    '2JOHN': '요한이서',
    '3JOHN': '요한삼서',
    'JUDE': '유다서',
    'REV': '요한계시록',
  };

  static String getBookName(String bookId) {
    return bookNames[bookId.toUpperCase()] ?? bookId;
  }
}
